[FEATURE] Create a Frontend Plugin without Extbase
FriendsOfTYPO3/blog_example pull request #35
Opened 2022-09-20 20:12 UTC by linawolf

based on https://in2code.de/aktuelles/hidden-objects-an-extbase-actions-uebergeben/

resolves #34
references TYPO3-Documentation/Changelog-To-Doc#8

2022-09-26 06:51 UTC, froemken requested changes

2022-09-26 06:51 UTC, froemken commented on Classes/Property/TypeConverters/HiddenCommentConverter.php
> +    protected function fetchObjectFromPersistence($identity, string $targetType): object
Use "Comment" as return type instead of "object"

2022-10-04 07:57 UTC, froemken requested changes

2022-10-04 07:57 UTC, froemken commented on Configuration/Services.yaml
> +
Remove one empty line

2022-10-04 07:57 UTC, froemken commented on Classes/Property/TypeConverters/HiddenCommentConverter.php
> +
Add Doc header

2022-10-04 14:52 UTC, linawolf commented on Configuration/Services.yaml
> +    tag:
```suggestion
    exclude: '../Classes/Domain/Model/*'
  FriendsOfTYPO3\BlogExample\Property\TypeConverters\HiddenCommentConverter:
    tag:
```

2022-10-04 14:54 UTC, merged